[collibra]
url="https://print.collibra.com/rest/2.0"
username="DataLakeAdmin"
password="gAAAAABj25XvTdPFpk9aAN_usnLFaQunAEJbnolg86X73IOx8JC77MS8uqzIzoEWHhXB33wfAjqetAvNDsi-LDdh273p0rxNcA=="

[collibra.metadata]
jobs=5
entries=10
least_files_strategy=true
seconds_to_wait=5 
location="./output"

[collibra.lineage]
location="./output"

[airflow]
url="http://localhost:8080/api/v1"
username="airflow"
password="airflow"

[runner.config.logging]
location="./logging.conf"

[runner.config.security]
key="W2.Collibra"

[runner.config.viewconfig]
location="./viewConfig.json"

[core]
default_scheduler_host="localhost"
default-scheduler-port=8082
